version: '1'

services:
  website:
    build:
      context: .
      target: dev
    env_file:
      - .env
    restart: "unless-stopped"
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./website:/app/website

  # Build a database container for the website to use.
  database:
    image: 'postgres:15'
    restart: "unless-stopped"
    ports:
      - 9004:9004
    volumes:
      - database-data:/var/lib/postgresql/data/ 
    environment:
      POSTGRES_USER: "deco-skill-issue"
      POSTGRES_PASSWORD: "deco-skill-issue"
      POSTGRES_DATABASE: "deco-skill-issue"

# We want database data to persist, so we put it into a volume.
volumes:
  database-data:
